# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20b39e545919db69ea30919212e24d4530c7afe7cc3110d3af5be09d8a07d34e1d4cc222f2b329b920a85e918c58b329a108c36991f0a9ac17f183a77589773f

test:
  secret_key_base: e8733b25b10b0221eb7598716baa781f6f52b47d46bc2a92fcd2bc6fbd0431273e6ffe1518c7a882761a2926ae30561319ee90b4ecdf72f8624da41f68de4fe2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
